"""Sales invoice types and refusals - FR-AR-001 .. FR-AR-004.

Mirrors migration 0037. Where this module and the database disagree, the
database is right - the same bargain `api.ledger.model` makes with 0020.
"""

from __future__ import annotations

import enum
import uuid
from collections.abc import Sequence
from dataclasses import dataclass, field
from datetime import date, datetime
from decimal import Decimal

from api.i18n.language import Language
from api.invoicing.duplicates import InvoiceDuplicateWarning
from api.invoicing.statutory import StatutoryFailure
from api.invoicing.vat import VatGroup
from api.vat.rules import TreatmentRole

__all__ = [
    "InvoiceStatus",
    "InvoiceLine",
    "SalesInvoice",
    "InvoiceView",
    "InvoicingError",
    "InvoiceNotFound",
    "InvoiceAlreadyIssued",
    "InvoiceNotIssued",
    "NotStatutoryCompliant",
    "NotAuthorizedToInvoice",
    "AlreadyCredited",
    "CreditNoteMismatch",
    "CustomerDetailsConflict",
]


class InvoiceStatus(enum.Enum):
    """Two states, and the transition between them is one-way.

    Mirrors 0037's CHECK. There is no `cancelled`: FR-AR-004 says an issued
    number cannot be reused, so a cancelled invoice is an issued invoice with a
    credit note against it - the record of what was claimed survives the
    correction of it.
    """

    DRAFT = "draft"
    ISSUED = "issued"


@dataclass(frozen=True, slots=True)
class InvoiceLine:
    """FR-AR-001's line item."""

    id: uuid.UUID
    position: int
    description: str
    quantity: Decimal
    unit_price: Decimal
    discount_percent: Decimal
    vat_treatment: str
    role: TreatmentRole
    #: Generated by the database from the three above. Never supplied.
    line_net: Decimal


@dataclass(frozen=True, slots=True)
class SalesInvoice:
    id: uuid.UUID
    organization_id: uuid.UUID
    administration_id: uuid.UUID
    fiscal_year_id: uuid.UUID
    status: InvoiceStatus
    #: None until issued. FR-AR-004.
    invoice_number: int | None
    number_prefix: str | None
    #: `prefix || number`, generated. What the customer quotes back.
    invoice_reference: str | None
    invoice_date: date
    supply_date: date | None
    due_date: date | None
    # Snapshotted at creation and frozen at issue (0037, 0039). Not joined
    # from the customer master: an invoice is a statutory record of what was
    # asserted on a date, and a customer who moves next year must not rewrite
    # a document already filed.
    customer_name: str
    customer_address: str
    customer_country: str
    customer_vat_number: str | None
    #: FR-AR-006. Provenance only - WHICH master record filled the snapshot in.
    #: None for a one-off customer typed straight onto the invoice, which is a
    #: permanently supported case (0039 keeps the column nullable).
    customer_id: uuid.UUID | None
    #: FR-TPL-013's recipient language, as it was when the invoice was raised.
    #: Snapshotted for the same reason the address is: art. 226(11)'s statement
    #: of why no VAT was charged is legal content, and a customer switching to
    #: English next year must not restate an invoice already in their hands.
    customer_language: Language
    credits_invoice_id: uuid.UUID | None
    notes: str | None
    issued_at: datetime | None
    #: FR-GL-006. The ledger entry this invoice produced, set once at issue in
    #: the same transaction (migration 0040). None on a draft, and on an invoice
    #: issued before 0040 - `invoicing.unposted_invoices()` finds those.
    journal_entry_id: uuid.UUID | None = None
    #: FR-TPL-017. The rendered PDF as issued, in the document archive. Set
    #: once; there is no re-render path.
    document_id: uuid.UUID | None = None
    lines: tuple[InvoiceLine, ...] = ()

    @property
    def is_draft(self) -> bool:
        return self.status is InvoiceStatus.DRAFT

    @property
    def is_credit_note(self) -> bool:
        return self.credits_invoice_id is not None

    @property
    def is_posted(self) -> bool:
        """Whether the books know about this invoice.

        Always true for an invoice issued since migration 0040 - `issue` posts
        in the same transaction. Worth asking anyway: an invoice issued before
        0040 answers False, and so would one issued by a future code path that
        broke the atomicity, which is the failure this property makes visible
        rather than silent.
        """
        return self.journal_entry_id is not None


@dataclass(frozen=True, slots=True)
class InvoiceView:
    """The invoice plus everything derived from it, computed once.

    The VAT groups and the legal wording travel WITH the invoice rather than
    being left for a caller to assemble, because getting either wrong produces
    a document that is non-compliant while looking entirely normal (FR-AR-002,
    FR-AR-003).
    """

    invoice: SalesInvoice
    groups: tuple[VatGroup, ...]
    net: Decimal
    vat: Decimal
    gross: Decimal
    #: One statement per treatment on the invoice, in the RECIPIENT's language
    #: (FR-TPL-013). Keyed by treatment code.
    wording: dict[str, str] = field(default_factory=dict)
    #: What would stop this being issued. Empty means it may be.
    statutory_failures: tuple[StatutoryFailure, ...] = ()
    #: True while any wording on this invoice has not been reviewed by a tax
    #: adviser. Surfaced rather than hidden - see api.invoicing.wording.
    wording_is_provisional: bool = True
    #: SI-12. Recent invoices to the same customer that look like this one. A
    #: WARNING and never a gate: `can_be_issued` below deliberately does not
    #: consult it. Empty on anything but a draft.
    duplicate_warnings: tuple[InvoiceDuplicateWarning, ...] = ()

    @property
    def can_be_issued(self) -> bool:
        return self.invoice.is_draft and not self.statutory_failures


class InvoicingError(Exception):
    """Base for this module's refusals."""


class InvoiceNotFound(InvoicingError):
    """No such invoice in this administration.

    Indistinguishable from "belongs to another tenant", and deliberately so:
    RLS filters it out either way, so this branch cannot tell and must not
    seem to.
    """


class InvoiceAlreadyIssued(InvoicingError):
    """The document has been asserted to somebody outside the business.

    Editing it now would change what they were told without changing what they
    hold. FR-AR-001's correction path is a credit note.
    """


class InvoiceNotIssued(InvoicingError):
    """Only an issued invoice can be credited - there is nothing to correct
    about a draft, which can simply be edited or deleted.
    """


class AlreadyCredited(InvoicingError):
    """A second credit note against one invoice would double the correction -
    the argument 0020 makes about reversing an entry twice.
    """


class CreditNoteMismatch(InvoicingError):
    """A credit note must credit an invoice of the same administration."""


class CustomerDetailsConflict(InvoicingError):
    """The request named a customer AND typed the details out by hand.

    Refused rather than resolved. Either answer - master wins, or payload wins
    - is defensible, and that is exactly the problem: whichever this code
    picked would be wrong for somebody, silently, on a statutory document. A
    caller who wants different details from the master record is describing a
    one-off customer and should send no `customer_id`.
    """

    def __init__(self, fields: tuple[str, ...]) -> None:
        self.fields = fields
        super().__init__(
            "this request names a customer_id and also supplies "
            f"{', '.join(fields)}. Send one or the other: the customer master "
            "fills these in (FR-AR-006)."
        )


class CustomerDetailsMissing(InvoicingError):
    """Neither a customer_id nor enough typed-in detail to address the invoice.

    Separate from `CustomerDetailsConflict` because it is the opposite fault
    and needs the opposite sentence - "you sent too much" and "you sent too
    little" share a route and nothing else. 0037 makes `customer_name` and
    `customer_address` NOT NULL and is right to: a document that cannot say who
    it is addressed to is not an invoice (FR-AR-003).
    """

    def __init__(self, fields: tuple[str, ...]) -> None:
        self.fields = fields
        super().__init__(
            f"an invoice needs {', '.join(fields)}, or a customer_id to take "
            "them from (FR-AR-003, FR-AR-006)."
        )


class NotStatutoryCompliant(InvoicingError):
    """FR-AR-003. Carries every failure, so a screen shows them at once."""

    def __init__(self, failures: Sequence[StatutoryFailure]) -> None:
        self.failures = tuple(failures)
        super().__init__(
            "this invoice is missing content Dutch law requires and cannot be "
            f"issued (FR-AR-003): {', '.join(f.field.value for f in self.failures)}"
        )


class NotAuthorizedToInvoice(InvoicingError):
    def __init__(self, action: str, resource_type: str, detail: str | None) -> None:
        self.action = action
        self.resource_type = resource_type
        self.detail = detail
        super().__init__(f"not authorized to {action} {resource_type}: {detail}")
