-- 0010_role_catalogue.sql
--
-- GENERATED FILE - DO NOT EDIT BY HAND.
-- Source of truth: apps/api/src/api/authz/matrix.py
-- Regenerate with: make generate-role-catalogue
--
-- The permission catalogue (PRD Appendix A's capability rows, one or two
-- permission triples each) and the twelve standard roles of PRD §8.4, with
-- the bundles Appendix A's matrix assigns them. matrix.py is checked against
-- prd.md itself by tests/authz/test_appendix_a_conformance.py, and this file
-- is checked against matrix.py by tests/authz/test_role_catalogue_generation.py,
-- so a change to the PRD, to the module, or to this file that is not made in
-- all three places fails CI.
--
-- Appendix A's "C" (conditional) cells grant the same permissions as "F".
-- The narrowing lives on the individual role_assignment's conditions column
-- (IAM-033) so it can vary per person - see matrix.py's CONDITIONAL_CELLS
-- and docs/decisions/ADR-011-authorization-model.md.

begin;

insert into permission (action, resource_type, resource_scope, description) values
    ('approve', 'expense', 'administration', 'Approve expenses'),
    ('approve', 'purchase_invoice', 'administration', 'Approve purchase invoices'),
    ('approve', 'sales_invoice', 'administration', 'Approve sales invoices'),
    ('close', 'fiscal_year', 'administration', 'Year-end close'),
    ('code', 'purchase_invoice', 'administration', 'Code purchase invoices'),
    ('create', 'payment_batch', 'administration', 'Create a payment batch'),
    ('create', 'sales_invoice', 'administration', 'Create sales invoices'),
    ('export', 'audit_log', 'administration', 'Export or stream the audit log'),
    ('export', 'report_data', 'administration', 'Export data'),
    ('file', 'vat_return', 'administration', 'File a VAT return'),
    ('lock', 'period', 'administration', 'Lock and unlock periods'),
    ('manage', 'bank_consent', 'administration', 'Connect and revoke bank consent'),
    ('manage', 'chart_of_accounts', 'administration', 'Maintain the chart of accounts'),
    ('manage', 'customer', 'administration', 'Manage customers'),
    ('post', 'journal_entry', 'administration', 'Post journal entries'),
    ('prepare', 'vat_return', 'administration', 'Prepare a VAT return'),
    ('read', 'audit_log', 'administration', 'Read an administration''s audit log'),
    ('reconcile', 'bank_transaction', 'administration', 'Reconcile bank transactions'),
    ('release', 'payment_batch', 'administration', 'Release payment to the bank'),
    ('reverse', 'journal_entry', 'administration', 'Reverse a posting'),
    ('send', 'sales_invoice', 'administration', 'Send sales invoices'),
    ('submit', 'expense', 'administration', 'Submit expenses'),
    ('upload', 'document', 'administration', 'Upload a source document'),
    ('view', 'administration', 'administration', 'View an administration'),
    ('view', 'bank_transaction', 'administration', 'View bank transactions'),
    ('view', 'chart_of_accounts', 'administration', 'View the chart of accounts'),
    ('view', 'document', 'administration', 'View source documents'),
    ('view', 'purchase_invoice', 'administration', 'View purchase invoices'),
    ('view', 'report', 'administration', 'View reports'),
    ('view', 'vat_return', 'administration', 'View prepared and filed VAT returns'),
    ('grant', 'firm_engagement', 'organization', 'Grant firm access to an administration'),
    ('manage', 'administration', 'organization', 'Create and archive administrations'),
    ('manage', 'api_client', 'organization', 'Manage API clients'),
    ('manage', 'billing', 'organization', 'Manage subscription and billing'),
    ('manage', 'organization_settings', 'organization', 'Manage organization settings'),
    ('manage', 'security_policy', 'organization', 'Manage MFA, session and IP policy'),
    ('manage', 'user_role', 'organization', 'Invite users and assign roles'),
    ('revoke', 'firm_engagement', 'organization', 'Revoke firm access'),
    ('run', 'access_review', 'organization', 'Run access reviews'),
    ('view', 'access_review', 'organization', 'View access review results'),
    ('view', 'api_client', 'organization', 'View API clients');

insert into "role" (name, scope_type, is_system) values
    ('Owner', 'organization', true),
    ('Organization Admin', 'organization', true),
    ('Security Admin', 'organization', true),
    ('Billing Admin', 'organization', true),
    ('Firm Manager', 'organization', true),
    ('Accountant', 'administration', true),
    ('Bookkeeper', 'administration', true),
    ('Approver', 'administration', true),
    ('Invoicer', 'administration', true),
    ('Expense Submitter', 'administration', true),
    ('Viewer', 'administration', true),
    ('Service Account', 'administration', true);

insert into role_permission (role_id, permission_id)
select r.id, p.id
from "role" r
join (values
    ('Owner', 'approve', 'expense'),
    ('Owner', 'approve', 'purchase_invoice'),
    ('Owner', 'approve', 'sales_invoice'),
    ('Owner', 'close', 'fiscal_year'),
    ('Owner', 'code', 'purchase_invoice'),
    ('Owner', 'create', 'payment_batch'),
    ('Owner', 'create', 'sales_invoice'),
    ('Owner', 'export', 'audit_log'),
    ('Owner', 'export', 'report_data'),
    ('Owner', 'file', 'vat_return'),
    ('Owner', 'grant', 'firm_engagement'),
    ('Owner', 'lock', 'period'),
    ('Owner', 'manage', 'administration'),
    ('Owner', 'manage', 'api_client'),
    ('Owner', 'manage', 'bank_consent'),
    ('Owner', 'manage', 'billing'),
    ('Owner', 'manage', 'chart_of_accounts'),
    ('Owner', 'manage', 'customer'),
    ('Owner', 'manage', 'organization_settings'),
    ('Owner', 'manage', 'security_policy'),
    ('Owner', 'manage', 'user_role'),
    ('Owner', 'post', 'journal_entry'),
    ('Owner', 'prepare', 'vat_return'),
    ('Owner', 'read', 'audit_log'),
    ('Owner', 'reconcile', 'bank_transaction'),
    ('Owner', 'release', 'payment_batch'),
    ('Owner', 'reverse', 'journal_entry'),
    ('Owner', 'revoke', 'firm_engagement'),
    ('Owner', 'run', 'access_review'),
    ('Owner', 'send', 'sales_invoice'),
    ('Owner', 'submit', 'expense'),
    ('Owner', 'upload', 'document'),
    ('Owner', 'view', 'access_review'),
    ('Owner', 'view', 'administration'),
    ('Owner', 'view', 'api_client'),
    ('Owner', 'view', 'bank_transaction'),
    ('Owner', 'view', 'chart_of_accounts'),
    ('Owner', 'view', 'document'),
    ('Owner', 'view', 'purchase_invoice'),
    ('Owner', 'view', 'report'),
    ('Owner', 'view', 'vat_return'),
    ('Organization Admin', 'grant', 'firm_engagement'),
    ('Organization Admin', 'manage', 'administration'),
    ('Organization Admin', 'manage', 'api_client'),
    ('Organization Admin', 'manage', 'organization_settings'),
    ('Organization Admin', 'manage', 'user_role'),
    ('Organization Admin', 'read', 'audit_log'),
    ('Organization Admin', 'revoke', 'firm_engagement'),
    ('Organization Admin', 'submit', 'expense'),
    ('Organization Admin', 'view', 'access_review'),
    ('Organization Admin', 'view', 'administration'),
    ('Organization Admin', 'view', 'api_client'),
    ('Security Admin', 'export', 'audit_log'),
    ('Security Admin', 'manage', 'security_policy'),
    ('Security Admin', 'read', 'audit_log'),
    ('Security Admin', 'run', 'access_review'),
    ('Security Admin', 'submit', 'expense'),
    ('Security Admin', 'view', 'access_review'),
    ('Security Admin', 'view', 'administration'),
    ('Security Admin', 'view', 'api_client'),
    ('Billing Admin', 'manage', 'billing'),
    ('Billing Admin', 'submit', 'expense'),
    ('Billing Admin', 'view', 'administration'),
    ('Firm Manager', 'grant', 'firm_engagement'),
    ('Firm Manager', 'manage', 'administration'),
    ('Firm Manager', 'manage', 'user_role'),
    ('Firm Manager', 'revoke', 'firm_engagement'),
    ('Firm Manager', 'submit', 'expense'),
    ('Firm Manager', 'view', 'administration'),
    ('Accountant', 'approve', 'expense'),
    ('Accountant', 'approve', 'purchase_invoice'),
    ('Accountant', 'close', 'fiscal_year'),
    ('Accountant', 'code', 'purchase_invoice'),
    ('Accountant', 'create', 'payment_batch'),
    ('Accountant', 'create', 'sales_invoice'),
    ('Accountant', 'export', 'report_data'),
    ('Accountant', 'file', 'vat_return'),
    ('Accountant', 'lock', 'period'),
    ('Accountant', 'manage', 'bank_consent'),
    ('Accountant', 'manage', 'chart_of_accounts'),
    ('Accountant', 'manage', 'customer'),
    ('Accountant', 'post', 'journal_entry'),
    ('Accountant', 'prepare', 'vat_return'),
    ('Accountant', 'read', 'audit_log'),
    ('Accountant', 'reconcile', 'bank_transaction'),
    ('Accountant', 'release', 'payment_batch'),
    ('Accountant', 'reverse', 'journal_entry'),
    ('Accountant', 'send', 'sales_invoice'),
    ('Accountant', 'submit', 'expense'),
    ('Accountant', 'upload', 'document'),
    ('Accountant', 'view', 'administration'),
    ('Accountant', 'view', 'bank_transaction'),
    ('Accountant', 'view', 'chart_of_accounts'),
    ('Accountant', 'view', 'document'),
    ('Accountant', 'view', 'purchase_invoice'),
    ('Accountant', 'view', 'report'),
    ('Accountant', 'view', 'vat_return'),
    ('Bookkeeper', 'code', 'purchase_invoice'),
    ('Bookkeeper', 'create', 'payment_batch'),
    ('Bookkeeper', 'create', 'sales_invoice'),
    ('Bookkeeper', 'export', 'report_data'),
    ('Bookkeeper', 'manage', 'bank_consent'),
    ('Bookkeeper', 'manage', 'chart_of_accounts'),
    ('Bookkeeper', 'manage', 'customer'),
    ('Bookkeeper', 'post', 'journal_entry'),
    ('Bookkeeper', 'prepare', 'vat_return'),
    ('Bookkeeper', 'reconcile', 'bank_transaction'),
    ('Bookkeeper', 'reverse', 'journal_entry'),
    ('Bookkeeper', 'send', 'sales_invoice'),
    ('Bookkeeper', 'submit', 'expense'),
    ('Bookkeeper', 'upload', 'document'),
    ('Bookkeeper', 'view', 'administration'),
    ('Bookkeeper', 'view', 'bank_transaction'),
    ('Bookkeeper', 'view', 'chart_of_accounts'),
    ('Bookkeeper', 'view', 'document'),
    ('Bookkeeper', 'view', 'purchase_invoice'),
    ('Bookkeeper', 'view', 'report'),
    ('Bookkeeper', 'view', 'vat_return'),
    ('Approver', 'approve', 'expense'),
    ('Approver', 'approve', 'purchase_invoice'),
    ('Approver', 'release', 'payment_batch'),
    ('Approver', 'submit', 'expense'),
    ('Approver', 'view', 'administration'),
    ('Approver', 'view', 'chart_of_accounts'),
    ('Approver', 'view', 'document'),
    ('Approver', 'view', 'purchase_invoice'),
    ('Approver', 'view', 'report'),
    ('Invoicer', 'create', 'sales_invoice'),
    ('Invoicer', 'manage', 'customer'),
    ('Invoicer', 'send', 'sales_invoice'),
    ('Invoicer', 'submit', 'expense'),
    ('Invoicer', 'upload', 'document'),
    ('Invoicer', 'view', 'administration'),
    ('Invoicer', 'view', 'chart_of_accounts'),
    ('Invoicer', 'view', 'document'),
    ('Expense Submitter', 'submit', 'expense'),
    ('Expense Submitter', 'upload', 'document'),
    ('Expense Submitter', 'view', 'administration'),
    ('Expense Submitter', 'view', 'document'),
    ('Viewer', 'export', 'report_data'),
    ('Viewer', 'read', 'audit_log'),
    ('Viewer', 'view', 'administration'),
    ('Viewer', 'view', 'bank_transaction'),
    ('Viewer', 'view', 'chart_of_accounts'),
    ('Viewer', 'view', 'document'),
    ('Viewer', 'view', 'purchase_invoice'),
    ('Viewer', 'view', 'report'),
    ('Viewer', 'view', 'vat_return'),
    ('Service Account', 'view', 'administration')
) as m(role_name, action, resource_type) on m.role_name = r.name
join permission p on p.action = m.action and p.resource_type = m.resource_type
where r.is_system;

commit;
