"""Serves the built React SPA (apps/web/dist) from the API's own origin.

ADR-063 decided LEDGR serves one origin - the API, the SPA, and stored file
bytes all come from the same host - and named this module's job as the
remaining work it left undone: "The API must serve the built SPA... Not done
in this ADR." The reason it has to be this way, not a separate static host,
is in ADR-063's own rejected-alternatives table: session cookies are
`SameSite=Strict` with no `domain=` (SEC-004), there is no CORS middleware in
api.main, and WebAuthn requires the browser to see every request as
same-origin with the page that called `navigator.credentials` - a second
hostname could not authenticate a user at all.

--- Why this is middleware, not a route ---

A route registered on `app` still passes through every middleware layer
between the request and the router - TenantContextMiddleware,
MfaEnforcementMiddleware, AuthorizationEnforcementMiddleware among them. Those
three exist to guard tenant data; an SPA asset or the app shell's `index.html`
is neither. Rather than teaching three separate security-critical files a
"this path is public" exemption (each with its own place that check could be
forgotten), SpaMiddleware sits OUTSIDE all of them and simply never calls
`call_next` for a non-API path - the request never reaches those layers, the
same way it never reaches them for a request Starlette itself can't route.
`api.main`'s middleware ordering comment records exactly where this is added
and why.

--- Why the CSP forced a real implementation, not a static file serve ---

api.security.headers.SecurityHeadersMiddleware's CSP is `script-src
'nonce-<random-per-request>' 'strict-dynanic'` - written, per its own
docstring, "for when [an HTML response] might [exist], rather than only for
the JSON responses that exist now." That now is this module: `index.html`
carries two `<script>` tags (the ADR-055 pre-paint theme script, inline, and
the built JS module), and under a nonce-based CSP an inline or external
script with no matching nonce simply does not run - so a byte-for-byte static
serve of `dist/index.html` would ship a page that never executes its own
script and never paints past the empty shell. `_index_response` reads the
build output once at import time and injects the CURRENT request's nonce
(already generated by SecurityHeadersMiddleware, upstream in the chain) into
every `<script` tag on each request, which is what makes it a template
instead of a static file, and why it has to run inside the CSP middleware
rather than in front of it.

--- Where the bytes come from in production ---

Deliberately NOT `apps/api/pyproject.toml`'s `force-include` mechanism the
way `api.i18n.catalogue` resolves the message catalogue: that requires the
source path to exist at `uv sync` time, and `apps/web/dist` is a BUILD
ARTIFACT, absent from a plain checkout - every API-only CI job (lint,
typecheck, test) runs `uv sync --frozen` without ever building the web app,
so force-including it would fail those jobs outright, not just leave the
SPA unavailable. `settings.web_dist_dir` (api.config) is the mechanism
instead: `apps/api/Dockerfile`'s web-build stage produces `apps/web/dist`,
copies it to a fixed path in the image, and sets the variable to point
there - an ordinary environment variable, resolved at runtime, with no
dependency on how the Python package itself was installed.

Unset (the common case: API-only local development, where Vite's own dev
server on :5173 proxies to this API on :8000 - see apps/web/vite.config.ts)
falls back to the checkout path, five directories up from this file. If
neither resolves to a real `index.html`, `register` leaves the middleware a
permanent no-op. Nothing here changes `/v1/*` or `/health` behaviour either
way.
"""

from __future__ import annotations

import re
from pathlib import Path

from fastapi import FastAPI, Request
from starlette.applications import Starlette
from starlette.middleware.base import BaseHTTPMiddleware, RequestResponseEndpoint
from starlette.responses import FileResponse, HTMLResponse, Response
from starlette.types import ASGIApp

from api.config import settings

#: Kept in step with api.authz_middleware.FRAMEWORK_PATHS by eye rather than
#: imported: that set exists to exempt these paths from the AUTHORIZATION
#: declaration check, this one exists to route them to the API instead of the
#: SPA shell, and the two lists happening to be the same set is coincidence,
#: not a shared contract - importing across modules for that would suggest a
#: dependency that isn't really there.
_FRAMEWORK_PATHS = frozenset({"/openapi.json", "/docs", "/docs/oauth2-redirect", "/redoc"})

_SCRIPT_TAG = re.compile(rb"<script\b")


def _is_api_path(path: str) -> bool:
    return path == "/health" or path.startswith("/v1/") or path in _FRAMEWORK_PATHS


def _candidate_dist_dirs() -> list[Path]:
    candidates = []
    if settings.web_dist_dir:
        candidates.append(Path(settings.web_dist_dir))
    here = Path(__file__).resolve()
    candidates.append(here.parents[4] / "apps" / "web" / "dist")  # the checkout
    return candidates


def _find_dist_dir() -> Path | None:
    for candidate in _candidate_dist_dirs():
        if (candidate / "index.html").is_file():
            return candidate
    return None


class SpaMiddleware(BaseHTTPMiddleware):
    """Added in api.main between CsrfProtectionMiddleware and
    SecurityHeadersMiddleware, so it runs AFTER the CSP nonce is generated
    (`request.state.csp_nonce`) but BEFORE tenant context, MFA, audit,
    idempotency or authorization ever see the request - see this module's
    docstring for why that ordering, not a route, is the mechanism.
    """

    def __init__(self, app: ASGIApp | Starlette, *, dist_dir: Path | None) -> None:
        super().__init__(app)
        self._dist_dir = dist_dir
        self._index_template = (
            (dist_dir / "index.html").read_bytes() if dist_dir is not None else None
        )

    def _index_response(self, nonce: str) -> HTMLResponse:
        assert self._index_template is not None
        html = _SCRIPT_TAG.sub(f'<script nonce="{nonce}"'.encode(), self._index_template)
        # SEC-005's private/no-store reasoning does not apply here - this is
        # the public app shell, identical for every visitor - but it must be
        # revalidated every load: it names the CURRENT build's hashed asset
        # filenames, and caching it past a deploy would serve a page that
        # asks for JS/CSS files that no longer exist.
        return HTMLResponse(html, headers={"Cache-Control": "no-cache"})

    async def dispatch(self, request: Request, call_next: RequestResponseEndpoint) -> Response:
        path = request.url.path
        if self._dist_dir is None or request.method not in ("GET", "HEAD") or _is_api_path(path):
            return await call_next(request)

        relative = path.lstrip("/")
        if relative:
            candidate = (self._dist_dir / relative).resolve()
            # The resolved candidate must still be INSIDE dist_dir - the
            # traversal guard a raw path segment (`../../etc/passwd`) needs,
            # since `relative` comes straight from the request URL.
            if candidate.is_file() and self._dist_dir in candidate.parents:
                headers = (
                    # Vite content-hashes every filename under assets/, so a
                    # given URL's bytes never change - safe to cache for as
                    # long as a browser will keep it, unlike index.html above.
                    {"Cache-Control": "public, max-age=31536000, immutable"}
                    if relative.startswith("assets/")
                    else None
                )
                return FileResponse(candidate, headers=headers)

        nonce = getattr(request.state, "csp_nonce", "")
        return self._index_response(nonce)


def register(app: FastAPI) -> None:
    app.add_middleware(SpaMiddleware, dist_dir=_find_dist_dir())
