import type { L } from "../l10n";

/**
 * The fixed, made-up sample data drawn inside the product mockups. Names, account numbers and
 * amounts are the same in both languages (Dutch bookkeeping terms stay Dutch); the labels around
 * them are translated. Illustration, not customer data: every mockup is `aria-hidden`.
 */
export const SAMPLE = {
  vendor: "Papierhuis Amsterdam",
  address: "Herengracht 112",
  stamp: "18-09-2026 14:32",
  item: { en: "Printer paper A4", nl: "Printerpapier A4" } as L,
  receiptTotal: { en: "Total", nl: "Totaal" } as L,
  vatLine: "BTW 21%",
  total: "EUR 52,80",
  lines: [
    { account: "4300 Kantoorkosten", debit: "43,64", credit: "" },
    { account: "1520 BTW te vorderen", debit: "9,16", credit: "" },
    { account: "1100 Bank", debit: "", credit: "52,80" },
  ],
  sum: "52,80",
};

export const MOCK = {
  url: "app.boeklite.nl/overview",
  nav: {
    overview: { en: "Overview", nl: "Overzicht" } as L,
    purchases: { en: "Purchases", nl: "Inkoop" } as L,
    bank: { en: "Bank", nl: "Bank" } as L,
    ledger: { en: "Grootboek", nl: "Grootboek" } as L,
    vat: { en: "BTW", nl: "BTW" } as L,
    reports: { en: "Reports", nl: "Rapportages" } as L,
  },
  capture: { en: "Capture receipt", nl: "Bon vastleggen" } as L,
  cash: { en: "Cash at bank", nl: "Saldo bank" } as L,
  cashAmount: "€ 18.240,15",
  vatDue: { en: "BTW due · Q3", nl: "BTW te betalen · Q3" } as L,
  vatAmount: "€ 2.104,50",
  vatBy: { en: "Due 31 Oct", nl: "Uiterlijk 31 okt" } as L,
  toBook: { en: "To book", nl: "Te boeken" } as L,
  toBookCount: "7",
  toBookSub: { en: "4 receipts · 3 bank lines", nl: "4 bonnen · 3 bankregels" } as L,
  todo: { en: "To do", nl: "Te doen" } as L,
  review: { en: "Review", nl: "Beoordelen" } as L,
  bankChip: { en: "Bank", nl: "Bank" } as L,
  ready: { en: "Ready", nl: "Klaar" } as L,
  todoBank: "NS Groep iDEAL",
  todoBankAmount: "−€ 38,40",
  todoVat: { en: "Q3 BTW return", nl: "BTW-aangifte Q3" } as L,
  todoVatWhen: { en: "25 days", nl: "25 dagen" } as L,
  receiptAmount: "€ 52,80",
  profit: { en: "Profit 2026", nl: "Winst 2026" } as L,
  profitAmount: "€ 41.880,00",
  detected: { en: "BTW 21% detected", nl: "BTW 21% herkend" } as L,
  account: { en: "Account", nl: "Rekening" } as L,
  debit: { en: "Debit", nl: "Debet" } as L,
  credit: { en: "Credit", nl: "Credit" } as L,
  balanced: { en: "Balanced to the cent", nl: "Sluitend tot op de cent" } as L,
  booked: { en: "Booked automatically", nl: "Automatisch geboekt" } as L,
  bankLines: [
    {
      initials: "NS",
      name: "NS Groep iDEAL",
      note: { en: "Matched to receipt · Reiskosten", nl: "Gekoppeld aan bon · Reiskosten" } as L,
      amount: "−38,40",
      incoming: false,
      attention: false,
    },
    {
      initials: "DV",
      name: "De Vries Holding B.V.",
      note: { en: "Invoice 2026-041 paid · Certain", nl: "Factuur 2026-041 betaald · Zeker" } as L,
      amount: "+1.210,00",
      incoming: true,
      attention: false,
    },
    {
      initials: "AH",
      name: "Albert Heijn 1402",
      note: { en: "No receipt yet · ask or skip", nl: "Nog geen bon · vragen of overslaan" } as L,
      amount: "−14,95",
      incoming: false,
      attention: true,
    },
    {
      initials: "KP",
      name: "KPN Zakelijk",
      note: {
        en: "Matched to receipt · Telefoon & internet",
        nl: "Gekoppeld aan bon · Telefoon & internet",
      } as L,
      amount: "−45,00",
      incoming: false,
      attention: false,
    },
  ],
  btwTitle: { en: "BTW-aangifte Q3 2026", nl: "BTW-aangifte Q3 2026" } as L,
  checked: { en: "Checked", nl: "Gecontroleerd" } as L,
  btwRows: [
    { label: "1a Leveringen/diensten belast met hoog tarief", amount: "3.420,00" },
    { label: "1b Leveringen/diensten belast met laag tarief", amount: "0,00" },
    { label: "4b Leveringen/diensten uit landen binnen de EU", amount: "21,00" },
    { label: "5b Voorbelasting", amount: "−1.336,50" },
  ],
  toPay: { en: "To pay", nl: "Te betalen" } as L,
  invoiceTitle: { en: "Invoice 2026-041", nl: "Factuur 2026-041" } as L,
  paid: { en: "Paid", nl: "Betaald" } as L,
  invoiceTo: { en: "To", nl: "Aan" } as L,
  invoiceCustomer: "De Vries Holding B.V.",
  invoiceLine: { en: "Design sprint, 2 days", nl: "Ontwerpsprint, 2 dagen" } as L,
  invoiceNet: "1.000,00",
  invoiceVat: "210,00",
  invoiceTotal: "€ 1.210,00",
  invoiceFoot: { en: "Sent 2 Sep · paid 9 Sep", nl: "Verstuurd 2 sep · betaald 9 sep" } as L,
  invoiceMatched: { en: "Matched from statement", nl: "Gekoppeld via afschrift" } as L,
  pnlTitle: { en: "Profit and loss · 2026", nl: "Winst-en-verlies · 2026" } as L,
  pnlPeriod: { en: "Jan – Sep", nl: "jan – sep" } as L,
  pnlRows: [
    { label: "Omzet", amount: "96.420,00" },
    { label: "Inkoopwaarde", amount: "−21.300,00" },
    { label: "Personeelskosten", amount: "−18.900,00" },
    { label: "Huisvesting", amount: "−7.200,00" },
    { label: "Overige kosten", amount: "−7.140,00" },
  ],
  result: { en: "Result", nl: "Resultaat" } as L,
  resultAmount: "41.880,00",
  journalTitle: { en: "Memoriaal · reversing entry", nl: "Memoriaal · tegenboeking" } as L,
  reversal: { en: "Reverses entry 0412", nl: "Draait boeking 0412 terug" } as L,
  linked: { en: "Linked to the original", nl: "Gekoppeld aan het origineel" } as L,
  clientsTitle: { en: "Client portfolio", nl: "Klantportefeuille" } as L,
  clientsCount: { en: "4 clients", nl: "4 klanten" } as L,
  open: { en: "Open", nl: "Geopend" } as L,
  clients: [
    {
      initials: "PA",
      name: "Papierhuis Amsterdam B.V.",
      kvk: "KvK 81234567",
      role: { en: "Bookkeeper", nl: "Boekhouder" } as L,
      colour: "#4f5bd5",
      open: true,
    },
    {
      initials: "SN",
      name: "Studio Noord",
      kvk: "KvK 72345678",
      role: { en: "Bookkeeper", nl: "Boekhouder" } as L,
      colour: "#0f8a7e",
      open: false,
    },
    {
      initials: "BV",
      name: "Bakkerij Vos",
      kvk: "KvK 63456789",
      role: { en: "Reviewer", nl: "Controleur" } as L,
      colour: "#c2410c",
      open: false,
    },
    {
      initials: "JG",
      name: "J. de Groot",
      kvk: "KvK 54567890",
      role: { en: "Bookkeeper", nl: "Boekhouder" } as L,
      colour: "#9d174d",
      open: false,
    },
  ],
  phoneRead: { en: "Read in 1.2 s", nl: "Gelezen in 1,2 s" } as L,
  phoneBook: { en: "Submit", nl: "Indienen" } as L,
};
